export const initialState = {
  mon: false,
  tue: false,
  wed: false,
  thu: false,
  fri: false,
  sat: false,
  sun: false,
  type: false,
  start: "07:00",
  end: "20:00",
  disableBtn: true,
  daysBeforeLesson: [],
  excludedUserDates: [],
};
